In [16]:
import numpy as np

a = np.array([3,5,7])
a1 = np.array([[1,2,3],[4,5,6]])
print(a)
print(a1)
print(a1[1][2])
print(np.arange(10))
print(a.ndim)
print(a1.ndim)
print(a1.shape)
print(len(a))

[3 5 7]
[[1 2 3]
 [4 5 6]]
6
[0 1 2 3 4 5 6 7 8 9]
1
2
(2, 3)
3


In [5]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrix.ndim)
print(matrix.shape)
print(matrix[1][3])

2
(3, 4)
8


In [ ]:
L = range(1000)
%timeit a**2 

In [8]:
L = np.arange(1000)
%timeit L**2

1.63 µs ± 202 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
matrix[1][1] = 100
matrix

array([[  1,   2,   3,   4],
       [  5, 100,   7,   8],
       [  9,  10,  11,  12]])

In [11]:
ls = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ls)
print(ls.shape)
print(ls.ndim)
print(ls[1][1][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
10


In [14]:
a = np.arange(1,10,3)
a

array([1, 4, 7])

In [16]:
ls = np.linspace(1,2,4)
ls

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [22]:
# The default data type for zeros and ones fn is float64
a = np.ones((3,3))
print(a)
#zeros
b = np.zeros((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
a = np.eye(2,3)
a

array([[1., 0., 0.],
       [0., 1., 0.]])

In [27]:
a = np.diag([1,2,3,4,5,6])
a

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [28]:
np.diag(a)

array([1, 2, 3, 4, 5, 6])

In [53]:
np.random.rand(5)

array([0.08333429, 0.48887179, 0.34654476, 0.94412332, 0.09681476])

In [30]:
a = np.random.randn(4)
a

array([ 1.23771959, -1.13921583, -1.33492049, -0.90119464])

In [32]:
a = np.arange(10, dtype = 'float64')
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [33]:
d = np.array([1+2j, 2+4j])
print(d.dtype)
d

complex128


array([1.+2.j, 2.+4.j])

In [34]:
b = np.array((True, False, True, False))
print(b.dtype)

bool


In [35]:
s = np.array(['sam','jon'])
print(s.dtype)

<U3


In [39]:
a = np.arange(10)
print(a[1:9:2])

[1 3 5 7]


In [38]:
a[5:] = 10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [40]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [18]:
a = np.arange(10)
b = a[::2]
c = a[::3]
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]


In [42]:
print(id(a))
print(id(b))
print(id(c))

2554050610544
2554043060592
2554046492816


In [19]:
print(np.may_share_memory(a,b))
print(np.may_share_memory(b,c))
print(np.may_share_memory(a,c))
print(np.shares_memory(a,b))

True
True
True
True


In [46]:
a = np.arange(10)
c = a[::2].copy()
np.may_share_memory(a,c)

False

## Pandas

In [1]:
import pandas as pd
df = pd.read_csv("C:/Users/Administrator/Desktop/UST campus training/nyc_weather.csv")
df.head(10)

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0   1/1/2016           38        23        52                 30.03   
1   1/2/2016           36        18        46                 30.02   
2   1/3/2016           40        21        47                 29.86   
3   1/4/2016           25         9        44                 30.05   
4   1/5/2016           20        -3        41                 30.57   
5   1/6/2016           33         4        35                 30.50   
6   1/7/2016           39        11        33                 30.28   
7   1/8/2016           39        29        64                 30.20   
8   1/9/2016           44        38        77                 30.16   
9  1/10/2016           50        46        71                 29.59   

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN   
1               10           7.0               0           3    NaN   
2               10           8.0               0           1    NaN   
3               10           9.0               0           3    NaN   
4               10           5.0               0           0    NaN   
5               10           4.0               0           0    NaN   
6               10           2.0               0           3    NaN   
7               10           4.0               0           8    NaN   
8                9           8.0               T           8   Rain   
9                4           NaN             1.8           7   Rain   

   WindDirDegrees  
0             281  
1             275  
2             277  
3             345  
4             333  
5             259  
6             293  
7              79  
8              76  
9             109

In [55]:
df.tail()

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
26               10           7.0               T           3   Rain   
27               10           5.0               0           1    NaN   
28               10           8.0               0           4    NaN   
29               10           7.0               0           0    NaN   
30               10           5.0               0           0    NaN   

    WindDirDegrees  
26             311  
27             234  
28             298  
29             257  
30             241

In [56]:
df.Events

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8         Rain
9         Rain
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15        Rain
16    Fog-Snow
17        Snow
18         NaN
19         NaN
20         NaN
21        Snow
22    Fog-Snow
23        Snow
24         NaN
25         NaN
26        Rain
27         NaN
28         NaN
29         NaN
30         NaN
Name: Events, dtype: object

In [64]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [59]:
df.WindSpeedMPH.isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
Name: WindSpeedMPH, dtype: bool

In [60]:
df.isna().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [62]:
df.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [65]:
df.Events.unique()

array([nan, 'Rain', 'Fog-Snow', 'Snow'], dtype=object)

In [66]:
df.Events.describe()

count        9
unique       3
top       Rain
freq         4
Name: Events, dtype: object

In [67]:
df['Temperature'].max()

50

In [68]:
df['Temperature'].min()

20

In [70]:
df1 = df['Temperature']>30
df1.sum()

22

In [72]:
df['EST'][df['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [3]:
df['EST'][df['Humidity']>=70]

8      1/9/2016
9     1/10/2016
15    1/16/2016
22    1/23/2016
Name: EST, dtype: object

In [4]:
df.describe()

Temperature   DewPoint   Humidity  Sea Level PressureIn  \
count    31.000000  31.000000  31.000000             31.000000   
mean     34.677419  17.838710  51.677419             29.992903   
std       7.639315  11.378626  11.634395              0.237237   
min      20.000000  -3.000000  33.000000             29.520000   
25%      29.000000  10.000000  44.500000             29.855000   
50%      35.000000  18.000000  50.000000             30.010000   
75%      39.500000  23.000000  55.000000             30.140000   
max      50.000000  46.000000  78.000000             30.570000   

       VisibilityMiles  WindSpeedMPH  CloudCover  WindDirDegrees  
count        31.000000     28.000000   31.000000       31.000000  
mean          9.193548      6.892857    3.129032      247.129032  
std           1.939405      2.871821    2.629853       92.308086  
min           1.000000      2.000000    0.000000       34.000000  
25%           9.000000      5.000000    1.000000      238.000000  
50%          10.000000      6.500000    3.000000      281.000000  
75%          10.000000      8.000000    4.500000      300.000000  
max          10.000000     16.000000    8.000000      345.000000

In [6]:
df['Events'].describe()

count        9
unique       3
top       Rain
freq         4
Name: Events, dtype: object

In [7]:
df.isna()

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0   False        False     False     False                 False   
1   False        False     False     False                 False   
2   False        False     False     False                 False   
3   False        False     False     False                 False   
4   False        False     False     False                 False   
5   False        False     False     False                 False   
6   False        False     False     False                 False   
7   False        False     False     False                 False   
8   False        False     False     False                 False   
9   False        False     False     False                 False   
10  False        False     False     False                 False   
11  False        False     False     False                 False   
12  False        False     False     False                 False   
13  False        False     False     False                 False   
14  False        False     False     False                 False   
15  False        False     False     False                 False   
16  False        False     False     False                 False   
17  False        False     False     False                 False   
18  False        False     False     False                 False   
19  False        False     False     False                 False   
20  False        False     False     False                 False   
21  False        False     False     False                 False   
22  False        False     False     False                 False   
23  False        False     False     False                 False   
24  False        False     False     False                 False   
25  False        False     False     False                 False   
26  False        False     False     False                 False   
27  False        False     False     False                 False   
28  False        False     False     False                 False   
29  False        False     False     False                 False   
30  False        False     False     False                 False   

    VisibilityMiles  WindSpeedMPH  PrecipitationIn  CloudCover  Events  \
0             False         False            False       False    True   
1             False         False            False       False    True   
2             False         False            False       False    True   
3             False         False            False       False    True   
4             False         False            False       False    True   
5             False         False            False       False    True   
6             False         False            False       False    True   
7             False         False            False       False    True   
8             False         False            False       False   False   
9             False          True            False       False   False   
10            False          True            False       False    True   
11            False         False            False       False    True   
12            False         False            False       False    True   
13            False         False            False       False    True   
14            False         False            False       False    True   
15            False         False            False       False   False   
16            False         False            False       False   False   
17            False         False            False       False   False   
18            False         False            False       False    True   
19            False         False            False       False    True   
20            False         False            False       False    True   
21            False          True            False       False   False   
22            False         False            False       False   False   
23            False         False            False   

In [14]:
for i in df.columns:
    print(i, df[i].dtypes)

EST object
Temperature int64
DewPoint int64
Humidity int64
Sea Level PressureIn float64
VisibilityMiles int64
WindSpeedMPH float64
PrecipitationIn object
CloudCover int64
Events object
WindDirDegrees int64


In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   EST                   31 non-null     object 
 1   Temperature           31 non-null     int64  
 2   DewPoint              31 non-null     int64  
 3   Humidity              31 non-null     int64  
 4   Sea Level PressureIn  31 non-null     float64
 5   VisibilityMiles       31 non-null     int64  
 6   WindSpeedMPH          28 non-null     float64
 7   PrecipitationIn       31 non-null     object 
 8   CloudCover            31 non-null     int64  
 9   Events                9 non-null      object 
 10  WindDirDegrees        31 non-null     int64  
dtypes: float64(2), int64(6), object(3)
memory usage: 2.8+ KB


In [15]:
df.index

RangeIndex(start=0, stop=31, step=1)