In [1]:
matrix = [
    [1,2,3,4],
    [6,8,3,4],
    [7,8,9,3]
]

newmatrix = []
for i in range(4):
    l = []
    for j in range(3):
        l.append(matrix[j][i])
    newmatrix.append(l)
for i in newmatrix:
    print(i)

[1, 6, 7]
[2, 8, 8]
[3, 3, 9]
[4, 4, 3]


In [2]:
import numpy as np
matrixx = np.array(matrix)
numpymatrix = matrixx.T
print(numpymatrix)

[[1 6 7]
 [2 8 8]
 [3 3 9]
 [4 4 3]]


In [3]:
x = [1,2,33]
y = x.copy()
print(id(x))
print(id(y))

2567972892224
2567972892480


In [4]:
#Assignment - how to reassign elements that are temporarily deleted from the set using pop
set1 = {1,2,3,4}
x = set1.pop()
set1.add(x)
print(set1)


{1, 2, 3, 4}
